/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    c_Deriva_Option_f: {
      address: "0x9fe46736679d2d9a65f0992f2272de9f3c7fa6e0",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "_daiAddr",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "approval",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
            {
              name: "designee",
              type: "address",
              internalType: "address",
            },
            {
              name: "purchaseId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "approvalAmount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "approve",
          inputs: [
            {
              name: "designee",
              type: "address",
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "purchaseId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "buyOptionByExactPremiumAndExpiry",
          inputs: [
            {
              name: "buyer",
              type: "address",
              internalType: "address",
            },
            {
              name: "seller",
              type: "address",
              internalType: "address",
            },
            {
              name: "token",
              type: "address",
              internalType: "address",
            },
            {
              name: "isCallOption",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "strikePrice",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "premium",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "expiry",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "amountPurchasing",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "purchaseResult",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "buyOptionByID",
          inputs: [
            {
              name: "buyer",
              type: "address",
              internalType: "address",
            },
            {
              name: "offerId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "amountPurchasing",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "purchaseResult",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "cancelOptionOffer",
          inputs: [
            {
              name: "offerId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "cancelResult",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "exerciseOption",
          inputs: [
            {
              name: "purchaseId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "exerciseResult",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "exerciseOptions",
          inputs: [
            {
              name: "purchaseIds",
              type: "uint256[]",
              internalType: "uint256[]",
            },
          ],
          outputs: [
            {
              name: "exerciseResult",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "getBlockNumber",
          inputs: [],
          outputs: [
            {
              name: "blockNumber",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getBlockTimestamp",
          inputs: [],
          outputs: [
            {
              name: "blockTimestamp",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getDaiToken",
          inputs: [],
          outputs: [
            {
              name: "dai",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getLastOrderId",
          inputs: [],
          outputs: [
            {
              name: "_lastOrderId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getLastPurchaseId",
          inputs: [],
          outputs: [
            {
              name: "_lastPurchaseId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "isOptionBuyable",
          inputs: [
            {
              name: "seller",
              type: "address",
              internalType: "address",
            },
            {
              name: "token",
              type: "address",
              internalType: "address",
            },
            {
              name: "isCallOption",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "strikePrice",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "premium",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "expiry",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "amountPurchasing",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "isBuyable",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "optionOffers",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "seller",
              type: "address",
              internalType: "address",
            },
            {
              name: "token",
              type: "address",
              internalType: "address",
            },
            {
              name: "isCallOption",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "strikePrice",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "premium",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "expiry",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "amountUnderlyingToken",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "offeredTimestamp",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "isStillValid",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "optionPurchases",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "buyer",
              type: "address",
              internalType: "address",
            },
            {
              name: "seller",
              type: "address",
              internalType: "address",
            },
            {
              name: "token",
              type: "address",
              internalType: "address",
            },
            {
              name: "isCallOption",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "strikePrice",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "premium",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "expiry",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "amountUnderlyingToken",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "offerId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "purchasedTimestamp",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "exercised",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "queryAllowances",
          inputs: [
            {
              name: "account",
              type: "address",
              internalType: "address",
            },
            {
              name: "spender",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "allowance",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "queryOrderbook",
          inputs: [
            {
              name: "seller",
              type: "address",
              internalType: "address",
            },
            {
              name: "token",
              type: "address",
              internalType: "address",
            },
            {
              name: "isCallOption",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "strikePrice",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "premium",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "expiry",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "_orderbook",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "queryPositions",
          inputs: [
            {
              name: "buyer",
              type: "address",
              internalType: "address",
            },
            {
              name: "token",
              type: "address",
              internalType: "address",
            },
            {
              name: "isCallOption",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "strikePrice",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "expiry",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "position",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "queryTokenActivated",
          inputs: [
            {
              name: "token",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "isTokenActivated",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "sellOption",
          inputs: [
            {
              name: "seller",
              type: "address",
              internalType: "address",
            },
            {
              name: "token",
              type: "address",
              internalType: "address",
            },
            {
              name: "isCallOption",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "strikePrice",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "_premiumPrice",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "_expirySeconds",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "amountUnderlyingToken",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "orderIdentifier",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "transfer",
          inputs: [
            {
              name: "recipient",
              type: "address",
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "purchaseId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "transferFrom",
          inputs: [
            {
              name: "from",
              type: "address",
              internalType: "address",
            },
            {
              name: "recipient",
              type: "address",
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "purchaseId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "Approval",
          inputs: [
            {
              name: "owner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "spender",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "value",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "purchaseId",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "OptionExercise",
          inputs: [
            {
              name: "optionId",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "exerciseCost",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "timestamp",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "OptionOffer",
          inputs: [
            {
              name: "seller",
              type: "address",
              indexed: false,
              internalType: "address",
            },
            {
              name: "token",
              type: "address",
              indexed: false,
              internalType: "address",
            },
            {
              name: "isCallOption",
              type: "bool",
              indexed: false,
              internalType: "bool",
            },
            {
              name: "strikePrice",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "premium",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "expiry",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "amountSelling",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "orderId",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "OptionPurchase",
          inputs: [
            {
              name: "buyer",
              type: "address",
              indexed: false,
              internalType: "address",
            },
            {
              name: "seller",
              type: "address",
              indexed: false,
              internalType: "address",
            },
            {
              name: "token",
              type: "address",
              indexed: false,
              internalType: "address",
            },
            {
              name: "isCallOption",
              type: "bool",
              indexed: false,
              internalType: "bool",
            },
            {
              name: "strikePrice",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "premium",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "expiry",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "amountPurchasing",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "purchaseId",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Transfer",
          inputs: [
            {
              name: "from",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "to",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "value",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "purchaseId",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "timestamp",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "ReentrancyGuardReentrantCall",
          inputs: [],
        },
      ],
      inheritedFunctions: {},
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
